### ISSUE TITLE
Review of the Project Requirements

### ISSUE THREAD

**Issue by Zulalm** [bounswe/bounswe2023group9#240]
### Issue Description

The project requirements should be revised.

### Deadline for the Issue

6.10.2023

**Comment by Zulalm** [comment]
I found some ambiguities in the project requirements. 
Firstly, I have questions about the notification options. Requirement 1.2.8.5 states that notifications shall be sent via e-mail if the chooses to receive notifications via e-mail. But there is not any requirement that allows users to choose any notification options. Furthermore, notification options are not clear. My suggestion is adding the following requirement:

- Basic users shall be able to choose to receive notifications via e-mail or receive as push notifications.

Secondly, the platform shall assign reviewers to the nodes randomly. But this requirement do not restrict contributors from reviewing their own nodes. Since it may reduce the reliability of the platform, we may add the following requirement :

- The platform shall not allow contributors to review their own nodes or objections.

**Comment by mehmetSuzer** [comment]
@Zulalm 
> * Basic users shall be able to choose to receive notifications via e-mail or receive as push notifications.

I think the push notification is something that we should already implement.  In addition, a user should also be able to choose to be notified via email. For instance, someone asked a question about your theorem. If you don't have the mobile app with notifications enabled, you cannot know about the question until you log in to your account in the web page. When you enter the web page, you should see that someone have a question. If you enable email notification, you should get an email telling that someone asked a question. By doing so, you can get notified about the activities in the platform without logging in.

**Comment by uyduranomer** [comment]
> I see an ambiguity in the requirements regarding the Wiki tags. The current requirements do not specify the process of generating these tags. It is unclear whether only admins can create them, or if reviewers and even contributors can also establish new ones. I think a couple of requirements can be written to clarify the creation of Wiki tags.

I remember that this was requested by product manager as anyone can add those tags. We may prefer disabling guest users to do that though. Let's discuss this with the product owner and decide later in the meeting.

> Additionally we may consider adding tags also for reference edges. As far as I remember, we have not discussed this topic before, so we can discuss whether we want this feature or not.

That's a great idea!

**Comment by uyduranomer** [comment]
I have some additions and comments on the current requirements:

- I think  guests should be able to view the wiki tags besides annotations and the others (1.1.1.1)
- I could not remember if we discussed and decided earlier but maybe basic users shall be able to follow other users (1.1.1.2)
- There is an ambiguity in 1.1.4.3. Which users shall have profile pages? (Obviously not the guests)
- As I mentioned in my previous comment and as mentioned by @Bera0422 , we should decide which user types are able to add wiki tags.
- The annotations added by reviewers are private or public? (1.1.1.4.3)
- Are admins able to perform all actions of contributors? Because this was not mentioned in the requirements, however was shown in the use-case diagrams. (1.1.1.5)
- I think admins shall not be able to delete or remove anything, they only may ban (disable) or hide something. In case of a misclick, a very important data would be lost  and can be undone according to  current requirements. (1.1.1.5)
- I think guests should be able to sign-up as shown in the use case diagram.  Therefore, a basic users shall be able to perform the same actions as guests except signing-up. (1.1.1.1)
- (1.2.1) I think nodes shall have public annotations as mentioned in the contributer part (1.1.1.3)
- (1.2.1) nodes shall be hidden in the graph
- I think @Zulalm was right on her mention:
> The platform shall not allow contributors to review their own nodes or objections.
- If 1.2.2.3, then in 1.1.1.4 we should add "reviewers shall be able to submit a report about their review"
- I could not understand 1.2.4.3
- I think we should remove the comments in 1.2.5.1.1. This would be a huge burden on the dbms
- In 1.2.6, how?
- We have to decide how 1.2.7 will be achieved
- @Zulalm 's first suggestion was already included in 1.1.4.8
- in 2.3.2, I think we should be more specific. We should explicitly mention that this prevention will be supplied by the reviewers, to prevent the misunderstanding of that it will be supplied by any software or an ai model
- 1.1.4 we should change the word "users" as "basic users"

**Comment by omerfaunal** [comment]
The notification feature introduces significant complexity and challenges during the initial stages of the project, with relatively limited added value to our application. Therefore, I recommend removing it from the requirements.

**Comment by Brunettow** [comment]
I have some comments on requirements. 

1.1.4.6 Users shall be able to edit their own profile.
-I think we can write "profile information" instead of "profile" to prevent ambiguity.

1.2.4 Annotation
-I would like to ask more about this part since I couldn't understand annotation part very well.

1.2.2.1 The platform shall assign some number of related and competent contributors for a node or objection as reviewers randomly 
-I think we should write "reviewer" instead of "contributer"

**Comment by ArslanArdavic** [comment]
Requirements wiki page is modified after in-team discussion.  Since our project is prone to emergence of new requirements or adjustments all members are welcomed to share opinion any time.

**Comment by Brunettow** [comment]
- In 1.1.1.4.1 instead of using the word "node", we can use "workspace"
- We can add this requirements: 
    - "Contributors shall be able to send collaboration request to other contributors."
    - "Reviewers shall be able to accept or reject  to view the requests which are submitted by contributors"

**Comment by uyduranomer** [comment]
All reviews are done, all necessary changes has been applied. The ones which needs discussions between the team and the product owner has been discussed in the lab today. The further updates for these will be done as the update task of the next week. The new issue has been opened ( #260 ). I am closing this issue.
