### ISSUE TITLE
Frontend technologies will be decided

### ISSUE THREAD

**Issue by uyduranomer** [bounswe/bounswe2023group9#249]
### Issue Description

Frontend and css technologies will be reserched and decided for the project.

### Steps

- [x] Research of proposed and probable technologies and their cons & pros
- [x] Discussion and deciding

### Deadline for the Issue

10.10.2023 - Tuesday - 17.00

**Comment by Brunettow** [comment]
Since we discussed earlier whether to use Flutter or React Native, I find this nice comparison chart. I hope it helps!
Also, After some research I still can't decide but I am slightly on React Native's side for now (Since it has a larger community)

<img src="https://github.com/bounswe/bounswe2023group9/assets/63921045/c8219b2a-8a8b-4316-bc08-e19babaef01c" width="500px;" >

src: https://www.simplilearn.com/tutorials/reactjs-tutorial/flutter-vs-react-native

**Comment by mehmetSuzer** [comment]
I found a nice video comparing Flutter and React Native. 

https://www.youtube.com/watch?v=X8ipUgXH6jw

**Comment by omerfaunal** [comment]
As a final decision, we decided to use using Flutter for the Frontend of our application.
