### ISSUE TITLE
Diagram Revision

### ISSUE THREAD

**Issue by Brunettow** [bounswe/bounswe2023group9#251]
### Issue Description

Recently requirements are changed. Diagrams shall be be revised due to those recent changes in requirements.

### Steps

- [x] [Revision of Use Case Diagram](https://github.com/bounswe/bounswe2023group9/wiki/Use-Case-Diagram)
- [x] [Revision of Class Diagram](https://github.com/bounswe/bounswe2023group9/wiki/Class-Diagram)
- [x] [Revision of Sequence Diagrams](https://github.com/bounswe/bounswe2023group9/wiki/Sequence-Diagrams)

### Deadline for the Issue

10.10.2023

**Comment by Zulalm** [comment]
I looked at the diagrams and I think we need to make a few changes. Here's what I found:

**Issues with the class diagram:**

*  Admin class inherits reviewer class on the class diagram. But according to the project requirements, admin user do not have the  capabilities of the reviewer. We can edit the class diagram after discussing the admin user permissions in the lab.
* Basic user has all the capabilities of the guest user except signing up. But basic user class do not inherit the guest class. I think we can create an abstract class that has all the capabilities of the guest user except signing up. Then, the guest and basic user classes inherit it.
*  A node can have exactly one workspace.
* Review class should have addComment function instead of addAnnotation function. Review class should not have a list of annotations. It may have a string attribute for the comment of the reviewer.
* Admin class should have a function to assign contributors as reviewers. 
 * There are approveWorkspace and rejectWorkspace functions in the workspace class. These functionalities should be provided in the reviewer class.
 
**Issues with the use case diagram:**

*  Search functions of the guest and basic user is not included.
* Assigning reviewers function is missing for the admin user.
* Contributors can create proof entry besides theorem entry.
* Reviewers cannot add/edit annotations. Reviewers can add/edit comments.

**Comment by Zulalm** [comment]
I updated the class diagram. The new version can be found at [Class Diagram](https://github.com/bounswe/bounswe2023group9/wiki/Class-Diagram)

**Comment by laylaylo** [comment]
hi @Zulalm, I've gone through your work, and it looks great! I noticed that you removed _approveWorkspace()_ but you might missed removing _rejectWorkspace()_ in the Workspace class.
In addition to your findings in previous comment, I've noticed that there is no function for assigning reviewer. I suggest adding an _AssignReviewer()_ function to ReviewRequest class since it should take place after a request being created.

**Comment by Zulalm** [comment]
I forgot to remove the rejectWorkspace() function. @laylaylo is right about the AssignReviewer() function. I uploaded the fixed version of the class diagram.

**Comment by laylaylo** [comment]
Comments and changes based on @Zulalm 's suggestions (in the same order):
- Guests and Basic User: cases for searching node and user are added 
- Regarding reviewer assignment by Admin, I haven't seen a specific requirement. As I understand, we'll discuss it in next meeting so I will add it depending our decision. For now, it seems that reviewer assignment is done by some algo automatically based on tags.
- I've updated 'theorem entry' to 'node entry', I think it includes both by this way. But I'm a little bit confused about this theorem/proof separation since there is no such separation in requirements but in class diagram. Actually, in glossary it is mentioned that "_node may be a theorem, conjecture, corollary, experience, observation, proof, law, formula_". Do you recall why we did do this separation in class diagram @Zulalm? We might want to simplify this.
- Reviewer: cases for editing and adding annotation are changed as editing and adding comment

My findings:
- Guests and Basic User: cases for viewing wiki tags and references of a node are added
- Admin: requirement about removing node is updated to removing/hiding node so corresponding case as well
- Admin: case for both removing proofs and nodes seems unusual to me. However, I seem to have forgotten the discussion about it. I'll bring this up in our next meeting to ensure we're on the same page.

**Comment by laylaylo** [comment]
Updated use case diagrams can be found [here](https://github.com/bounswe/bounswe2023group9/wiki/Use-Case-Diagram)

**Comment by Brunettow** [comment]
I am reviewing and updating the Sequential Diagrams according to mock-ups and updated requirements.
 I decided to make core changes to the Reviewer's diagrams. I think they fit better to the requirements and mock-ups now.
> You can see the updated version below, I would like to ask you before updating the diagram.

## Old Version
![DeepinScreenshot_select-area_20231010013754](https://github.com/bounswe/bounswe2023group9/assets/63921045/72694e27-3013-4237-a19f-9069b24cd068)

## New Version
![DeepinScreenshot_select-area_20231010014111](https://github.com/bounswe/bounswe2023group9/assets/63921045/3948f635-6380-43f5-bc69-52d53b69bd5d)

**Comment by Brunettow** [comment]
I would like to add those diagrams to sequential diagrams after receiving your reviews.

- 1.1.1.3.5 Contributors shall be able to issue an objection against a node.
![DeepinScreenshot_select-area_20231010024804](https://github.com/bounswe/bounswe2023group9/assets/63921045/cecf4797-2a7b-4370-93ce-4ed93bbbbf70)

- 1.1.1.3.4 Contributors shall be able to create public annotations for the nodes they create.
![DeepinScreenshot_select-area_20231010030020](https://github.com/bounswe/bounswe2023group9/assets/63921045/0cc776ff-3217-41ef-82d7-81a9c92e0e42)

**Comment by Brunettow** [comment]
It seems like I misunderstood the requirement 1.1.1.3.5 which was "Contributors shall be able to issue an objection against a node Contributors shall be able to issue an objection against a node". Here is the updated version:
![DeepinScreenshot_select-area_20231010132651](https://github.com/bounswe/bounswe2023group9/assets/63921045/507cd3ff-2fe2-4ce5-8c69-c9b56cb8f323)

**Comment by Zulalm** [comment]
I reviewed your work @Brunettow and it looks great! I have a minor comment on the sequence diagram of the reviewer. As we clarified on the last meeting, reviewers cannot add annotations to nodes. Reviewer can add comments to node entries. Related requirement is 1.1.1.4.3.

**Comment by Zulalm** [comment]
All inconsistencies on the diagrams are fixed before the lab meeting. UML diagrams might be rearranged after the project requirements are revised based on what we discussed in the meeting. Related issue is #261.
