### ISSUE TITLE
Contributor

### ISSUE THREAD

**Issue by ArslanArdavic** [bounswe/bounswe2023group9#27]

**Comment by uyduranomer** [comment]
The diagram has been shared in the lucidcharts workspace.
Issue needs review asap to be closed.

**Comment by laylaylo** [comment]
Hey @uyduranomer, I took a look at your work, it seems like a good design and logically correct. Good job! 

However, I think some points are missing. Let me explain them here briefly. Contributors can only send notifications but never get one such as get question, get collaboration invitation, node review accepted/rejected and so on. 

You may think just stating sending notifications will be sufficient since every received notification is sent by someone. But since there are two sides of this interaction, I believe they are needed to be stated as well. Please let me know if you think they are redundant and if so, explain your reasoning.

 I also added my suggested sub-chart into bottom-left of Contributor page related to this missing part (not sure about arrows though).

**Comment by uyduranomer** [comment]
> Hey @uyduranomer, I took a look at your work, it seems like a good design and logically correct. Good job! 
> 
> 
> 
> However, I think some points are missing. Let me explain them here briefly. Contributors can only send notifications but never get one such as get question, get collaboration invitation, node review accepted/rejected and so on. 
> 
> 
> 
> You may think just stating sending notifications will be sufficient since every received notification is sent by someone. But since there are two sides of this interaction, I believe they are needed to be stated as well. Please let me know if you think they are redundant and if so, explain your reasoning.
> 
> 
> 
>  I also added my suggested sub-chart into bottom-left of Contributor page related to this missing part (not sure about arrows though). 

Thanks for the valuable comments, you have made a good point. We will evaluate these in the next meeting and work on them soon.

**Comment by hakanaktas0** [comment]
This part of the use case diagram is reviewed and ready to be merged.
