### ISSUE TITLE
Profile Page GET API

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#285]
### Issue Description

GET API for Profile page should be implemented.

### Steps

- [x] API implementation
- [x] Test implementation
- [x] PR created
- [x] PR merged

### Deadline for the Issue

22.10.2023 - Sunday - 23.59

**Comment by Brunettow** [comment]
Settings part is designed.
Previous Design was not coherent with app theme so I changed according to discussions.
There can be minor changes on web design, especially on app bar since we discussed that to have a general app bar for website.
### Current Design:
![DeepinScreenshot_google-chrome_20231023134505](https://github.com/bounswe/bounswe2023group9/assets/63921045/1ac3310d-9367-4f3b-962b-bafec2c08b67)

**Comment by hakanaktas0** [comment]
Profile Page GET API has been implemented and merged.
