### ISSUE TITLE
FE - Research Latex and MD renderer

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#431]
### Issue Description

Research Latex and MD renderer
### Steps

- [x] Research Flutter Tex
- [x] Research MD flutter
- [ ] Report findings: state challenges

### Deadline for the Issue

21.11.2023 17.00

**Comment by laylaylo** [comment]
here are my findings for [Flutter Tex](https://pub.dev/packages/flutter_tex):
- Implementation seems straightforward
- Potential concern regarding efficiency: we need it for Node's Theorem part in graph page (only one container) and Node's Theorem and Proofs part in node view page (couple of containers). So I think, bottleneck would be node view page.

Since implementation appears not complicated, I plan do a demo for node view page on weekend and observe its impact on rendering and uploading page. 
(Note: need to try it with a node having long Latex theorems&proofs --> create demo node)

**Comment by omerfaunal** [comment]
As I understand it, in order to render LaTeX using Flutter Tex, the entire widget tree needs to be a Tex widget. This implies changing both the parent and child widgets on the page. This is one of my concerns, but please try it, and let's see the results; maybe this is not the case.

Additionally, please consider how we can implement annotations with a LaTeX view. Currently, we can select a text part, right-click, and it fetches the current position of the word, showing the annotation menu. Can we achieve the same functionality with LaTeX? How we can select something in Latex? If you try to select and copy something in Wikipedia, it sends unformatted, weird (not in Latex format) texts.

**Comment by laylaylo** [comment]
@omerfaunal I tried it and figured out that the entire widget tree does not need to be a Tex widget. It is possible to add TexView() widget only for theorem part instead of a Text() widget. 

However child widgets of it should be Tex so I couldn't find a way to integrate with AnnotationText() widget, because it also does not accept a child widget. But I believe there should be a way of solving it, either modifying AnnotationText() widget a little bit or maybe directly using annotation feature of latex. Let's make a quick call to discuss this, as I have limited knowledge about AnnotationText!

**Comment by omerfaunal** [comment]
Yes, while implementing AnnotationText I also noticed that it is going to be challenging to use this with Tex widgets. We may figure this out after implementing Tex widgets if you are offering to use them.

**Comment by laylaylo** [comment]
We decided to move on with [flutter_tex](https://pub.dev/packages/flutter_tex). It has several renderer engines with quality - speed trade-off. While rendering time for math-related content appears acceptable, last [changes in flutter_tex](https://pub.dev/packages/flutter_tex/changelog) seems old and it's not well maintained to support so many things. It's challenging adding annotations to math formulas and needs some way around, which introduces a potential risk. Research is complete, implementation will be done upcoming weeks.
