### ISSUE TITLE
FE - Create Workspace Provider

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#475]
### Issue Description

A provider should be implemented to connect the workspace page with backend. 

### Steps

- [x] Implement Workspace Provider
- [x] PR

### Deadline for the Issue

28.11.2023

**Comment by Zulalm** [comment]
A provider for the workspace page is implemented and PR is ready to review. But the provider is not tested comprehensively due to the lack of the testing data. The provider should be tested while connecting to the workspace. If you encounter any issues related with the provider, please mention it under this issue.

**Comment by Zulalm** [comment]
I assigned @Brunettow by mistake.

**Comment by omerfaunal** [comment]
Here are my comments on PR. Please check them. These are critical things to discuss about.

https://github.com/bounswe/bounswe2023group9/pull/502#issuecomment-1826425384

**Comment by Zulalm** [comment]
I checked your comments and made the necessary changes on the provider. Since the PR is approved and merged, this issue might be closed.
