### ISSUE TITLE
Learning Best Practices for GitHub Issue Labels and Creating Required Labels

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#5]
**Aim** : make easier to get information about the issue by searching a particular label attached to it

These are the label categories we decided to create: 

- [x] Priority

- [x] Effort/Size 

- [x] Type

- [x] Status

Github documentation about [managing labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels).
[This blog](https://seantrane.com/posts/logical-colorful-github-labels-18230/) might be helpful.

**Comment by hakanaktas0** [comment]
I propose for priority,

- priority: Low
- priority: Medium
- priority: High
- priority: Critical

It is hard to state size for sure, so I think we can instead use Estimation,
What each of these represent (S~2 hours etc.) can be decided later by the team.

- Estimation: S
- Estimation: M
- Estimation: L
- Estimation: XL

For type,
More can and should be added, but since we don't do any software development yet, we don't need labels like bug or test-fail.

- type: documentation
- type: enhancement
- type: research
- type: repository

For status,

- status: to-do
- status: in-progress
- status: needs-review
- status: in-review
- status: completed
- status: postponed

Color coding is also important.
Any suggestions and additions are welcome.

**Comment by defabdullah** [comment]
I think the tags suggested by the Hakan will be enough. If there is no other recommendation, we can create them.

**Comment by laylaylo** [comment]
Few small addition, `status: blocked` and `type: question`. Also, we might create platform labels like `platform: web`,` platform: android` but I guess it's better to do it when it's needed i.e before implementation phase.

Instead of **estimation** tag, I suggest adding **difficulty** and **size**. Since estimating duration of a task is also challenging and we should have a common way to do that. Indeed, difficulty and size tags could help us to estimate total time would taken by task. My suggestions to these tags:

- Difficulty: starter
- Difficulty: medium
- Difficulty: challenging

- Size: small
- Size: medium
- Size: large

I would like to hear other opinions about estimation or difficulty/size tags. After reaching a consensus, I'll create labels as discussed.

**Comment by ArslanArdavic** [comment]
It's a good idea to distinguish difficulty and size. More we separate the functionality of labels, better we describe the issues.

**Comment by laylaylo** [comment]
As discussed offline, we agreed on size and difficulty labels. The time required for a task might be estimated using these labels as follows: 

- small and easy: 1-2 hours
- small and moderate: 2-4 hours
- small and challenging: 4-6 hours
- medium and easy: 1-2 days
- medium and moderate: 2-4 days
- medium and challenging: 4-6 days
- large and easy: 1-2 weeks
- large and moderate: 2-4 weeks
- large and challenging: 4-8 weeks or more

Of course, these are just suggestions, and we can adjust them as we go along.

**Comment by laylaylo** [comment]
For future reference, please always put a description for labels and consider color coding.
