### ISSUE TITLE
FE - Annotation Implementation 

### ISSUE THREAD

**Issue by omerfaunal** [bounswe/bounswe2023group9#565]
### Issue Description

Annotation Implementation 

### Steps

- [x] Read W3C annotation standards
- [x] Research Flutter Selectable Texts, Selection Region, TexView, Widget Tree on two environment, Context Builder, BrowserContextMenu 
---------------
- [x] Implement different solutions locally
- [x] Check those implementations with dummy latex if it works
- [x] Share your results
- [x] If not works, find another solution and repeat the cycle :)

If everything works as expected we will start implementation afterwards.

Possible difficulties: 
Latex renderer creates it's own widget tree preventing us from changing context menu which is the menu that shows up on right click.

### Deadline for the Issue

19.12.2023

**Comment by ThoAppelsin** [comment]
What do you mean "start"? Didn't we already see some start at the M2 presentation? Was it all fake?

**Comment by omerfaunal** [comment]
@ThoAppelsin Maybe the start is not a good phrase for this case. In M2 we created the skeleton, the UI part. Now we need to implement all the mechanisms to connect it to the backend services, retrieve it, parse it etc.

In the meeting, because we didn't have much time to discuss all the details, I left the name as it is and said "Let's meet up later and decide how to proceed" We left the steps empty, we will also fill them after deciding how to proceed.

Still I'm changing it to generic format, Annotation Implementation

**Comment by omerfaunal** [comment]
Here are what I tried on my local environment this week. 

1 - Tried to convert latex view to Selectable Text, it was unsuccessful. 
2 - Tried to wrap latex view with my own designed AnnotationText Widget, however still same problem occurs. I can't change LatexView's own widget tree. This was unsuccessful. 

Also I researched on W3C standards. So when backend ready, we will be able to connect backend and frontend easily. However it is still not possible to directly show the annotation in frontend.

We need to keep trying for next week.

**Comment by laylaylo** [comment]
I've come across with [flutter_math](https://github.com/znjameswu/flutter_math) and investigated it. At first sight, it seems like it will probably have the same problems as _flutter_math_, however it is worth to try it quickly and see if it's more flexible than our current implementation. 

I haven't had the time past week to check it in detail but I will continue to work on this next week.

**Comment by laylaylo** [comment]
After using flutter_math instead of flutter_tex on my local, I see that it has the same limitations as flutter_tex. Then in their repo I checked in detail whether in-line equations is possible, because they promised it [here](https://github.com/znjameswu/flutter_math/blob/master/doc/line_breaking.md). That's was the reason why flutter_math got my attention. But after investigation, I found out that even in-line equations/line breaking were their intention they didn't implement them. [See issue.](https://github.com/znjameswu/flutter_math/issues/8). As I understand from discussion, somebody already tried hard to achieve what we wanted even with hardcoded text (i.e no need to search and find equation in text), and they didn't add it to supported library. Realize this [flutter_math](https://github.com/znjameswu/flutter_math) has its last changes 3 years ago :( another disappointing not much supported library..

**Comment by ThoAppelsin** [comment]
Dropping in, I hope you don't mind. (I have been receiving notifications on this thread since I got involved once.)

In summary, I think we cannot make flutter, latex rendering, and annotations work together. Latex rendering and annotations are requirements of the project, and the project won't be certified as "successfully developed" until the requirements are met, and on time. Flutter is not a requirement, so, ultimately, with the current set of requirements, we should do away with the flutter. However, you will definitely be late if you try to do that now, which will also make the project unsuccessful. (I trust you could do it on time if you could take a break from all your other responsibilities, but you cannot and should not, so I suggest that you don't.)

The only way this project can become successful now seems to be through changing the requirements. **You may not do away with any one of the requirements no matter the reason/rationale, that is beyond your authority.** You could talk with the project owners and try convince them to change the requirements. It is actually very late for that now, but you don't seem to have any other option.

**Comment by ThoAppelsin** [comment]
I almost forgot: Thanks for all your efforts to try making it work, I personally really appreciate it. The harsh truth is that this research, apparently, had to be done sooner and we should have stayed away from flutter or at least be done away with it sooner (after finding out that it cannot accommodate latex and annotations simultaneously, through feasibility analysis). It's ok though, and actually great that we did this mistake here and lose only some points, so we hopefully won't do it again later and lose some well-paying customers.

**Comment by omerfaunal** [comment]
As a final approach I implemented Latex Renderer and Annotation as two different features in the same page. One way or another, we can both display Latex and annotate the necessary formulas. Maybe not in the best way but in a parallel way with requirements.

Provider (Backend connection) is not yet implemented because backend not ready. It will be next week's job.

**Comment by omerfaunal** [comment]
Merged to the frontend
