### ISSUE TITLE
Bug - Multiple Latex Proofs, shown as blank

### ISSUE THREAD

**Issue by laylaylo** [bounswe/bounswe2023group9#635]
Only last added proof is seen, other becomes an empty box.

**Comment by laylaylo** [comment]
Problem is investigated, pasting description of PR also here:

### **Issue**

When there is more than one proof for a node, only last one is visible in latex and others seen as blank.

**Problem**: rendering issue of flutter_tex

### **Possible Root Causes & Tried Solutions**
- giving time for rendering as delay (was not sufficient alone)
- ListView.builder may cause an issue due to stateful widget so I changed it to non-built in customize list (was not sufficient alone)
- in order to give time for rendering and also enhance user-friendliness(1 tasla 2 kus), I changed the functionality of `show annotation/show text` buttons, now they are working for each proof independently. (probably this one is the real solver)

**Comment by omerfaunal** [comment]
I successfully addressed the mentioned bug by altering the page layout, converting widgets to TexColumn, and modifying the annotation mechanism. The bug is now completely fixed, eliminating the need for any workarounds. To achieve this, I created additional widgets for their own environment specifically designed for Tex widgets.

Merged
